name: Universal Docker CI

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the private repo to clone (e.g. org/private-repo)"
        required: true
      branch:
        description: "Branch to build from"
        required: false
        default: main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: ${{ github.event.inputs.repo_name }}
      BRANCH: ${{ github.event.inputs.branch }}
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Set all values
        run: |
          echo "::add-mask::${REPO_NAME}"
          echo "::add-mask::${GITHUB_PAT}"
          echo "::add-mask::${DOCKER_USER}"
          echo "::add-mask::${DOCKER_PASS}"

      - name: Clone private repo (silent)
        run: |
          git clone -q https://${GITHUB_PAT}@github.com/${REPO_NAME}.git app
          cd app
          git checkout -q ${BRANCH}

      - name: Build Docker image (silent)
        working-directory: ./app
        run: |
          docker build -t ghcr.io/${REPO_NAME,,}:latest . > /dev/null 2>&1
          docker tag ghcr.io/${REPO_NAME,,}:latest ${DOCKER_USER}/${REPO_NAME,,}:latest > /dev/null 2>&1

      - name: Test Docker image (10s timeout)
        working-directory: ./app
        run: |
          docker run -d --name test_container ghcr.io/${REPO_NAME,,}:latest > /dev/null 2>&1 || exit 1
          sleep 10
          docker stop test_container > /dev/null 2>&1 || true
          docker rm test_container > /dev/null 2>&1 || true

      - name: Login to GitHub Container Registry
        run: |
          echo "${GITHUB_PAT}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin > /dev/null 2>&1

      - name: Push to GitHub Container Registry (silent)
        run: |
          docker push ghcr.io/${REPO_NAME,,}:latest > /dev/null 2>&1

      - name: Login to Docker Hub
        run: |
          echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin > /dev/null 2>&1

      - name: Push to Docker Hub (silent)
        run: |
          docker push ${DOCKER_USER}/${{ steps.repo.outputs.short_name }}:latest > /dev/null 2>&1
