name: Universal Docker CI

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the private repo to clone (e.g. org/private-repo)"
        required: true
      branch:
        description: "Branch to build from"
        required: false
        default: main

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.inputs.repo_name }}
      BRANCH: ${{ github.event.inputs.branch }}
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Clone private repo
        run: |
          git clone https://${GITHUB_PAT}@github.com/${REPO_NAME}.git app
          cd app
          git checkout ${BRANCH}

      - name: Build Docker image
        working-directory: ./app
        run: |
          docker build -t ghcr.io/${REPO_NAME,,}:latest .

      - name: Test Docker image
        working-directory: ./app
        run: |
          docker run --rm ghcr.io/${REPO_NAME,,}:latest

      - name: Login to GitHub Container Registry
        run: |
          echo "${DOCKER_PASS}" | docker login ghcr.io -u "${DOCKER_USER}" --password-stdin

      - name: Push to GitHub Container Registry
        run: |
          docker push ghcr.io/${REPO_NAME,,}:latest
