name: Universal Docker CI
on:
  repository_dispatch:
    types: [trigger-build]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_tag: ${{ steps.vars.outputs.sha_short }}
      env_tag: ${{ steps.vars.outputs.env_tag }}
      moving_tag: ${{ steps.vars.outputs.moving_tag }}
    env:
      OWNER_NAME: ${{ github.event.client_payload.owner_name }}
      REPO_NAME: ${{ github.event.client_payload.repo_name }}
      BRANCH: ${{ github.event.client_payload.branch || 'main' }}
      DEVOPS_REPO: ${{ github.event.client_payload.devops_repo || 'devops' }}
      DEVOPS_BRANCH: ${{ github.event.client_payload.devops_branch || 'main' }}
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_CLUSTER_NAME: ${{ secrets.AZURE_CLUSTER_NAME }}
    steps:
      - name: Clone private repo
        run: |
          git clone https://${GITHUB_PAT}@github.com/${OWNER_NAME}/${REPO_NAME}.git app
          cd app
          git checkout ${BRANCH}
      
      - name: Get short commit SHA and determine tags
        id: vars
        run: |
          cd app
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          if [ "${BRANCH}" = "main" ]; then
            echo "env_tag=prod" >> $GITHUB_OUTPUT
            echo "moving_tag=latest" >> $GITHUB_OUTPUT
          elif [ "${BRANCH}" = "dev" ]; then
            echo "env_tag=dev" >> $GITHUB_OUTPUT
            echo "moving_tag=dev" >> $GITHUB_OUTPUT
          else
            echo "env_tag=${BRANCH}" >> $GITHUB_OUTPUT
            echo "moving_tag=${BRANCH}" >> $GITHUB_OUTPUT
          fi

      - name: Clone devops repo
        run: |
          git clone https://${GITHUB_PAT}@github.com/${OWNER_NAME}/${DEVOPS_REPO}.git devops
          cd devops
          git checkout ${DEVOPS_BRANCH}
      
      - name: Execute build script
        env:
          COMMIT_TAG: ${{ steps.vars.outputs.sha_short }}
          ENV_TAG: ${{ steps.vars.outputs.env_tag }}
          MOVING_TAG: ${{ steps.vars.outputs.moving_tag }}
        run: |
          cd devops
          chmod +x build.sh
          bash build.sh
      
      - name: Execute deployment script
        env:
          IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}-${{ steps.vars.outputs.env_tag }}
          ENV_TAG: ${{ steps.vars.outputs.env_tag }}
        run: |
          export IMAGE_REPO="${DOCKER_USER}/${REPO_NAME,,}"
          cd devops/${REPO_NAME}
          chmod +x deploy.sh
          bash deploy.sh
